export type ProjectDateLocale = 'en' | 'lt'

export function resolveProjectDateLocale(value: string | null | undefined): ProjectDateLocale {
  return String(value ?? '').trim().toLowerCase().startsWith('lt') ? 'lt' : 'en'
}

export const projectDateStrings = {
  en: {
    projectDate: 'Project date',
    chooseProjectDate: 'Choose project date',
    votingInProgress: 'Voting in progress',
    projectDateUndecided: 'Project date has not been decided yet.',
    everyoneResponded: 'Everyone has responded',
    everyoneRespondedOrganizerHelp: 'Everyone has responded. You can choose the final date now or wait until voting closes.',
    everyoneRespondedParticipantHelp: 'Everyone has responded. The organizer can choose the final date now, or Date Finder will finalize the result when voting closes.',
    selectFinalDateNow: 'Select final date now',
    chooseFinalDate: 'Choose final date',
    confirmFinalDateTitle: 'Confirm final date',
    confirmFinalDate: 'Set this as the final date',
    confirmFinalDateHelp: 'Participants will no longer be able to change their date availability.',
    waitForDeadline: 'Or wait for Date Finder to finalize the result when voting closes.',
    currentResult: 'Current result',
    currentlyTied: 'Currently tied',
    allRespondedHelp: 'Participants can still update their responses until the voting deadline. The leading option will be selected when voting closes.',
    tiedUntilDeadlineHelp: 'These options are currently tied. If the tie remains when voting closes, the organizer will choose the final date.',
    waitingForOrganizerDecision: 'These options are tied. Waiting for the organizer to choose the final date.',
    votingCloses: 'Voting closes',
    editResponsesAndOptions: 'Edit responses and date options',
    viewDateDetails: 'View date details',
    dateConfirmed: 'Confirmed',
    confirmedParticipants: 'Participants confirmed',
    chooseDatesHelp: 'Choose the dates when you can participate.',
    chooseDates: 'Choose dates',
    responded: 'participants responded',
    ends: 'Ends',
    available: 'Available',
    maybe: 'Maybe',
    unavailable: 'Unavailable',
    preferred: 'Preferred',
    preferredHelp: 'You can prefer one date that you marked available.',
    currentlyBest: 'Currently best option',
    suggestedBy: 'Suggested by',
    suggestAnother: 'Suggest another date',
    suggestionsClosed: 'New suggestions closed; responses stay open until the deadline.',
    removeDate: 'Remove date',
    start: 'Start date',
    endOptional: 'End date (optional)',
    dates: 'Dates',
    selectDates: 'Select dates',
    chooseEndDate: 'Choose end date',
    sameDay: 'Same day',
    clearDates: 'Clear',
    done: 'Done',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    startDateSelected: 'Start date selected',
    endDateSelected: 'End date selected',
    addDate: 'Add date',
    cancel: 'Cancel',
    dateAlreadySuggested: 'This date has already been suggested.',
    dateVoting: 'Date voting',
    missingResponses: 'Missing responses',
    sendReminder: 'Send reminder',
    organizerDecision: 'Organizer decision required',
    organizerDecisionHelp: 'Available and preferred votes are tied. Choose one of the tied dates.',
    selectDate: 'Select this date',
    closeVoting: 'Calculate result now',
    confirmed: 'Confirmed',
    awaitingConfirmation: 'Awaiting confirmation',
    cannotAttend: 'Cannot attend',
    minimumParticipants: 'Minimum participants',
    moreNeeded: 'more confirmed participant needed',
    moreNeededPlural: 'more confirmed participants needed',
    canYouAttend: 'Can you attend?',
    finalProjectDate: 'Final project date',
    projectTime: 'Project time',
    timeNotSet: 'No time set yet.',
    addTime: 'Add time',
    editTime: 'Edit time',
    startTime: 'Start time',
    endTimeOptional: 'End time (optional)',
    saveTime: 'Save time',
    clearTime: 'Remove time',
    yesAttend: 'Yes, I will attend',
    noAttend: 'No, I cannot attend',
    stillDontKnow: "I still don't know",
    selectedDateDoesNotWork: 'The selected project date does not work for you.',
    leaveProject: 'Leave project',
    stayObserver: 'Stay as observer',
    joinProject: 'Join this project',
    projectFull: 'The project is at capacity.',
    confirmationDeadline: 'Confirmation deadline',
    saveDeadline: 'Save deadline',
    noDateOptions: 'No dates have been suggested yet.',
    priorityTask: 'Priority task',
    awaitingNames: 'Awaiting confirmation',
    notifications: 'Date notifications',
    responseSaved: 'Response saved.',
  },
  lt: {
    projectDate: 'Projekto data',
    chooseProjectDate: 'Pasirinkite projekto datą',
    votingInProgress: 'Vyksta balsavimas',
    projectDateUndecided: 'Projekto data dar nenuspręsta.',
    everyoneResponded: 'Visi atsakė',
    everyoneRespondedOrganizerHelp: 'Visi dalyviai atsakė. Galite pasirinkti galutinę datą dabar arba palaukti balsavimo pabaigos.',
    everyoneRespondedParticipantHelp: 'Visi dalyviai atsakė. Organizatorius gali pasirinkti galutinę datą dabar arba Date Finder užfiksuos rezultatą pasibaigus balsavimui.',
    selectFinalDateNow: 'Pasirinkti galutinę datą dabar',
    chooseFinalDate: 'Pasirinkti galutinę datą',
    confirmFinalDateTitle: 'Patvirtinti galutinę datą',
    confirmFinalDate: 'Nustatyti kaip galutinę datą',
    confirmFinalDateHelp: 'Po patvirtinimo dalyviai nebegalės keisti savo pasirinkimų dėl datos.',
    waitForDeadline: 'Arba palaukite, kol pasibaigus balsavimui Date Finder užfiksuos rezultatą.',
    currentResult: 'Dabartinis rezultatas',
    currentlyTied: 'Šiuo metu lygios',
    allRespondedHelp: 'Dalyviai gali keisti atsakymus iki balsavimo termino. Pirmaujantis variantas bus pasirinktas pasibaigus balsavimui.',
    tiedUntilDeadlineHelp: 'Šie variantai šiuo metu surinko vienodai balsų. Jei pasibaigus balsavimui rezultatas nesikeis, galutinę datą pasirinks organizatorius.',
    waitingForOrganizerDecision: 'Šie variantai surinko vienodai balsų. Laukiama, kol organizatorius pasirinks galutinę datą.',
    votingCloses: 'Balsavimas baigiasi',
    editResponsesAndOptions: 'Keisti atsakymus ir datų variantus',
    viewDateDetails: 'Peržiūrėti datos informaciją',
    dateConfirmed: 'Patvirtinta',
    confirmedParticipants: 'Patvirtinę dalyvavimą',
    chooseDatesHelp: 'Pažymėkite datas, kada galite dalyvauti.',
    chooseDates: 'Pasirinkti datas',
    responded: 'dalyviai atsakė',
    ends: 'Baigiasi',
    available: 'Galiu',
    maybe: 'Galbūt',
    unavailable: 'Negaliu',
    preferred: 'Pageidaujama',
    preferredHelp: 'Galite pasirinkti vieną pageidaujamą datą, kurią pažymėjote „Galiu“.',
    currentlyBest: 'Šiuo metu geriausias variantas',
    suggestedBy: 'Pasiūlė',
    suggestAnother: 'Pasiūlyti kitą datą',
    suggestionsClosed: 'Naujų datų siūlymas baigtas; atsakymus galima keisti iki termino.',
    removeDate: 'Pašalinti datą',
    start: 'Pradžios data',
    endOptional: 'Pabaigos data (nebūtina)',
    dates: 'Datos',
    selectDates: 'Pasirinkti datas',
    chooseEndDate: 'Pasirinkite pabaigos datą',
    sameDay: 'Ta pati diena',
    clearDates: 'Išvalyti',
    done: 'Baigti',
    previousMonth: 'Ankstesnis mėnuo',
    nextMonth: 'Kitas mėnuo',
    startDateSelected: 'Pasirinkta pradžios data',
    endDateSelected: 'Pasirinkta pabaigos data',
    addDate: 'Pridėti datą',
    cancel: 'Atšaukti',
    dateAlreadySuggested: 'Ši data jau buvo pasiūlyta.',
    dateVoting: 'Balsavimas dėl datos',
    missingResponses: 'Trūkstami atsakymai',
    sendReminder: 'Siųsti priminimą',
    organizerDecision: 'Reikalingas organizatoriaus sprendimas',
    organizerDecisionHelp: 'Dalyvavimo ir pageidavimo balsai sutampa. Pasirinkite vieną iš lygių datų.',
    selectDate: 'Pasirinkti šią datą',
    closeVoting: 'Apskaičiuoti rezultatą dabar',
    confirmed: 'Patvirtino',
    awaitingConfirmation: 'Laukiama patvirtinimo',
    cannotAttend: 'Negali dalyvauti',
    minimumParticipants: 'Minimalus dalyvių skaičius',
    moreNeeded: 'trūksta vieno patvirtinto dalyvio',
    moreNeededPlural: 'trūksta patvirtintų dalyvių',
    canYouAttend: 'Ar galite dalyvauti?',
    finalProjectDate: 'Galutinė projekto data',
    projectTime: 'Projekto laikas',
    timeNotSet: 'Laikas dar nenustatytas.',
    addTime: 'Pridėti laiką',
    editTime: 'Keisti laiką',
    startTime: 'Pradžios laikas',
    endTimeOptional: 'Pabaigos laikas (nebūtina)',
    saveTime: 'Išsaugoti laiką',
    clearTime: 'Pašalinti laiką',
    yesAttend: 'Taip, dalyvausiu',
    noAttend: 'Ne, negaliu dalyvauti',
    stillDontKnow: 'Vis dar nežinau',
    selectedDateDoesNotWork: 'Pasirinkta projekto data jums netinka.',
    leaveProject: 'Palikti projektą',
    stayObserver: 'Likti stebėtoju',
    joinProject: 'Prisijungti prie projekto',
    projectFull: 'Projekte nebėra vietų.',
    confirmationDeadline: 'Patvirtinimo terminas',
    saveDeadline: 'Išsaugoti terminą',
    noDateOptions: 'Dar nepasiūlyta nė viena data.',
    priorityTask: 'Prioritetinė užduotis',
    awaitingNames: 'Laukiama patvirtinimo',
    notifications: 'Datos pranešimai',
    responseSaved: 'Atsakymas išsaugotas.',
  },
} as const

export function getProjectDateStrings(locale: ProjectDateLocale) {
  return projectDateStrings[locale]
}
