import type { ProjectDateLocale } from './projectDateStrings'

export const projectFinanceStrings = {
  en: {
    sharedCosts: 'Shared costs',
    sharedCostsHelp: 'Choose whether this project should manage money.',
    organizeOnly: 'Organize only',
    organizeOnlyDescription: 'No payments or balances will be managed in this project. Participants can settle costs separately or in person.',
    manageSharedCosts: 'Manage shared costs',
    manageSharedCostsDescription: 'Use commitments, payments, balances and shared project expenses.',
    enableSharedCosts: 'Enable shared cost management',
    disableSharedCosts: 'Organize without managed finance',
    financeHistoryBlocked: 'Financial management cannot be disabled because this project already has financial activity.',
    projectProgress: 'Project progress',
    confirmedParticipants: 'confirmed participants',
    nextAction: 'Next action',
    inviteMore: 'Invite one more participant',
    inviteMorePlural: 'Invite more participants',
    participationReady: 'Minimum participation reached',
    participants: 'participants',
    date: 'Date',
    responses: 'Responses',
    confirmed: 'confirmed',
    awaitingConfirmation: 'awaiting confirmation',
    cannotAttend: 'cannot attend',
    notSet: 'Not set',
    paymentRecipient: 'Payment recipient',
    paymentRecipientHelp: 'Add the payment destination required to enable managed shared costs.',
    paymentRecipientPlaceholder: 'Payment URL or IBAN',
    join: 'Join',
    joinProject: 'Join project',
    joined: 'Joined',
    notJoined: 'Not joined',
    noJoinedParticipants: 'No joined participants',
    notInterested: 'Not interested',
  },
  lt: {
    sharedCosts: 'Bendros išlaidos',
    sharedCostsHelp: 'Pasirinkite, ar šiame projekte bus valdomi pinigai.',
    organizeOnly: 'Organizuoti be finansų',
    organizeOnlyDescription: 'Šiame projekte mokėjimai ir balansai nebus valdomi. Dalyviai gali atsiskaityti atskirai arba gyvai.',
    manageSharedCosts: 'Valdyti bendras išlaidas',
    manageSharedCostsDescription: 'Naudoti įsipareigojimus, mokėjimus, balansus ir bendras projekto išlaidas.',
    enableSharedCosts: 'Įjungti bendrų išlaidų valdymą',
    disableSharedCosts: 'Organizuoti be valdomų finansų',
    financeHistoryBlocked: 'Finansų valdymo išjungti negalima, nes šiame projekte jau yra finansinės veiklos.',
    projectProgress: 'Projekto eiga',
    confirmedParticipants: 'patvirtinti dalyviai',
    nextAction: 'Kitas veiksmas',
    inviteMore: 'Pakvieskite dar vieną dalyvį',
    inviteMorePlural: 'Pakvieskite daugiau dalyvių',
    participationReady: 'Minimalus dalyvių skaičius pasiektas',
    participants: 'dalyviai',
    date: 'Data',
    responses: 'Atsakymai',
    confirmed: 'patvirtino',
    awaitingConfirmation: 'laukia patvirtinimo',
    cannotAttend: 'negali dalyvauti',
    notSet: 'Nenustatyta',
    paymentRecipient: 'Mokėjimų gavėjas',
    paymentRecipientHelp: 'Pridėkite mokėjimo paskirties duomenis, reikalingus bendrų išlaidų valdymui įjungti.',
    paymentRecipientPlaceholder: 'Mokėjimo nuoroda arba IBAN',
    join: 'Prisijungti',
    joinProject: 'Prisijungti',
    joined: 'Prisijungta',
    notJoined: 'Neprisijungta',
    noJoinedParticipants: 'Dalyvių dar nėra',
    notInterested: 'Nedomina',
  },
} as const

export function getProjectFinanceStrings(locale: ProjectDateLocale) {
  return projectFinanceStrings[locale]
}
